name: Deploy Application

on:
  push:
    branches:
      - main  # 仅监听 main 分支的提交

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检查出仓库代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 将代码上传到服务器并部署
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.164.136.151 << 'EOF'
            cd /var/www/
            git pull origin main  # 拉取最新代码
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
